In [55]:
"""
Advent of Code 2018
https://adventofcode.com/2018

Day 3
Part 1
"""

#Set up
import pandas as pd
df = pd.read_csv('input', header=None, sep= " ", 
                 names=['ClaimID', '@', 'Start', 'Size']).drop(columns=['@'])

df.ClaimID = df.ClaimID.str.replace("#", "")
df.Start = [pd.to_numeric(coord) for coord in df.Start.str.replace(":", "").str.split(",")]
df.Size = [pd.to_numeric(dim) for dim in df.Size.str.split("x")]

df.head()

ClaimID       Start      Size
0       1  [387, 801]  [11, 22]
1       2  [101, 301]  [19, 14]
2       3  [472, 755]  [11, 16]
3       4  [518, 720]  [23, 17]
4       5  [481, 939]  [29, 20]

In [61]:
import numpy as np

def map_claim(start, size, 
              fabric_size = (1000, 1000)):
    start_zeros = np.zeros( (start[1], start[0]), dtype=int )
    top_zeros = np.zeros( (start[1], fabric_size[0] - start[0]), dtype=int )
    left_zeros = np.zeros( (size[1], start[0]), dtype=int )
    right_zeros = np.zeros( (size[1], fabric_size[0] - start[0] - size[0]), dtype=int )
    bottom_zeros = np.zeros( (fabric_size[1] - size[1] - start[1], fabric_size[0]), dtype=int )
    
    claim_matrix = np.ones( (size[::-1]), dtype=int )

    return np.block([[start_zeros, top_zeros], 
                    [left_zeros, claim_matrix, right_zeros], 
                   [bottom_zeros]])



In [68]:
fabric = np.zeros( (1000, 1000), dtype=int )
for index, row in df.head().iterrows():
    fabric += map_claim(row.Start, row.Size)
    
print(fabric)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [70]:
overlap = np.sum(np.where(fabric > 1, 1, 0))
print(overlap)

0
